[ISSUE-125] Update operator documentation
dell/csi-baremetal-operator pull request #126
Opened 2022-04-26 11:50 UTC by AnnaDutova

Signed-off-by: Dutova <Ann.Dutova@Dell.com>

## Purpose
### Issue #125 

Due to proposal dell/csi-baremetal#806 need to add steps for manual patching scheduler on k3s

## PR checklist
- [x] Add link to the issue
- [x] Choose Project
- [x] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
Was already tested in  dell/csi-baremetal#806

2022-04-27 08:12 UTC, misanthropicat approved these changes

2022-04-27 08:21 UTC, safronovD commented on docs/MANUAL_SCHEDULER_CONFIGURATION.md
> +    * For manual patching folow next instructions
typo _follow_ and _the instructions below_ is better

2022-04-27 08:21 UTC, safronovD commented on docs/MANUAL_SCHEDULER_CONFIGURATION.md
> +    * For manual patching folow next instructions
Please add _for all master nodes_

2022-04-27 08:21 UTC, safronovD commented on docs/MANUAL_SCHEDULER_CONFIGURATION.md
> +        ```
`yaml` here can help to colorize listings for popular MD files viewers

2022-04-27 08:21 UTC, safronovD commented on docs/MANUAL_SCHEDULER_CONFIGURATION.md
> +        apiVersion: kubescheduler.config.k8s.io/v1beta1
Please add that we should use `kubescheduler.config.k8s.io/v1beta3` for k8s 1.23 and above

2022-04-28 11:08 UTC, safronovD approved these changes

2022-04-28 11:18 UTC, mishoyama requested changes

2022-04-28 11:18 UTC, mishoyama commented on docs/MANUAL_SCHEDULER_CONFIGURATION.md
> +* K3S
Please add reference on this to main README.md

2022-05-05 08:00 UTC, mishoyama approved these changes

2022-05-05 08:49 UTC, merged